name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rohithreddykota
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York

          # Language plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: ipynb, qs, cs, html, css, md
          plugin_languages_limit: 5

          # # Achievements plugin workaround
          # plugin_achievements: yes
          # plugin_achievements_display: compact
          # plugin_achievements_threshold: C
          # plugin_achievements_ignored: manager

          # # Other plugins
          # plugin_followup: yes
          # plugin_followup_sections: user
          # plugin_stars: yes
          # plugin_stars_limit: 4
          # plugin_topics: yes
          # plugin_topics_mode: icons
          # plugin_topics_limit: 15
          # plugin_topics_sort: stars
          # plugin_lines: yes
          # plugin_repositories: yes
          # plugin_repositories_featured: rohithreddykota/rill-developer
